### ISSUE TITLE
Adding support to Loader

### ISSUE THREAD

**Issue by walkermatt** [mixedbredie/highways-for-pgrouting#1]
Hi Ross,

I'm planning on adding support for OS Highways to Loader. From your experience working with the data are the tables produced by the FME Workbenches about right? Is there anything you'd change to make life easier?

I'd like to do a good job of importing all of the data into Postgres with a view to building a network in pgRouting.

Cheers,

Matt.

**Comment by mixedbredie** [comment]
I'll check, Matt.
I had a similar request for .gfs files at a recent OS Highways workshop.
Cheers
Ross

**Comment by mixedbredie** [comment]
I've mailed you the tables (created by FME) directly that I used to create the network.
